Frontend/restore/src/app/components/navbar/navbar.jsx
=> feature: added navbar component

Backend/.env, Backend/src/Database/DB_connection.js, Backend/src/app.js, Backend/src/index.js
=> feat:Levantando Server

Backend/src/Database/models/userModel.js
Agregue el codigo postal y meti la carpeta de models a database
=> correcionEsquemaUsuario

Backend/src/Controllers/controllersTecnologias.js, Backend/src/Database/models/Technology.js, Backend/src/Routes/tecnologia.js
=> feat: 6 rutas get creadas / subcategoria endPoint 

Backend/src/Controllers/controllersUser.js, Backend/src/Routes/index.js, Backend/src/Routes/userRouter.js
termine las rutas de user con un get que trae todos los usuarios, uno que trae un usuario por id, un put que cambia la contraseña y un post para crear un usuario
=> Ruta user Vfinal

Backend/src/Controllers/disableProduct.js, Backend/src/Database/models/Technology.js, Backend/src/Routes/tecnologia.js
Creado 11:47 a ver cuanto demoramos en mergear je
=> feat:rutas put y get de disabled products

Backend/src/Controllers/controllersTecnologias.js, Backend/src/Controllers/ofertas.js, Backend/src/Database/models/Technology.js, Backend/src/Routes/tecnologia.js, Frontend/restore/src/app/components/card/card.jsx, Frontend/restore/src/app/home/[category]/page.jsx, Frontend/restore/src/app/home/[category]/page.module.css, Frontend/restore/src/app/home/fetch.js, Frontend/restore/src/app/home/page.jsx, Frontend/restore/src/app/page.jsx
borrado de endpoints y controllers de categorias que no se usaban
=> Categoria update

Backend/src/Controllers/controllersTecnologias.js, Backend/src/Controllers/ofertas.js, Backend/src/Database/models/Technology.js, Backend/src/Routes/tecnologia.js, Frontend/restore/src/app/components/card/card.jsx, Frontend/restore/src/app/home/[category]/page.jsx, Frontend/restore/src/app/home/[category]/page.module.css, Frontend/restore/src/app/home/fetch.js, Frontend/restore/src/app/home/page.jsx, Frontend/restore/src/app/page.jsx
le pedi a lucas una ruta dinamica para que se haga un poco mas facil por ahora las peticiones, despues incorporare las otras, se incorporo el fetch por cada categoria, tuve que cambiar un poco la ruta ofertas porque traia todos los productos.
=> ruta categorias

Frontend/restore/src/app/components/loader/Loader.css, Frontend/restore/src/app/components/loader/Loader.jsx, Frontend/restore/src/app/components/order/order.jsx, Frontend/restore/src/app/home/[category]/[productId]/FetchDetail.jsx, Frontend/restore/src/app/home/[category]/[productId]/page.jsx, Frontend/restore/src/app/home/[category]/page.jsx
falta importarlo en las paginas
=> componente loader

Frontend/restore/next.config.js, Frontend/restore/src/app/components/ProductsContainer/ProductsContainer.jsx, Frontend/restore/src/app/components/searchbar/searchbar.jsx, Frontend/restore/src/app/home/page.jsx, Frontend/restore/src/app/page.jsx
me quede en la branch searchbar para hacer la landing je
=> Landing terminada

Backend/src/Controllers/searchName.js, Frontend/restore/src/app/components/ProductsContainer/ProductsContainer.jsx, Frontend/restore/src/app/components/navbar/navbar.jsx, Frontend/restore/src/app/components/searchbar/searchbar.jsx, Frontend/restore/src/app/form/form.modules.css, Frontend/restore/src/app/form/page.jsx, Frontend/restore/src/app/home/[category]/[productId]/FetchDetail.jsx, Frontend/restore/src/app/home/[category]/page.jsx, Frontend/restore/src/app/home/fetch.js, Frontend/restore/src/app/home/page.jsx, Frontend/restore/src/app/page.jsx, Frontend/restore/src/app/search/page.jsx, package-lock.json
Refactorizado de searchbar, agregado de mayusculas y minusculas  en la search endpoint hecho por luca ,  cambie la carpeta del form para cambiar la ruta, el codigo del css del form esta comentado de momento porque me rompia la navbar
=> Search bar2

Backend/src/Controllers/controllersTecnologias.js, Backend/src/utils/multer.js, Frontend/restore/src/app/form/page.jsx
formulario completado con subida de imagen
=> formulario cloudinary

Frontend/restore/next.config.js
=> next config

Backend/src/Controllers/controllersTecnologias.js, Backend/src/Controllers/controllersUser.js, Backend/src/Database/models/userModel.js, Backend/src/Routes/userRouter.js
Agregue rutas para actualizar los datos de los usuarios, ademas de agregar al modelo de user la opcion de poner una foto de perfil con sus rutas correspondientes para subirla y actualizarla
=> Rutas para actualizar datos de usuario

Backend/package-lock.json, Backend/package.json, Backend/src/Controllers/carrito.js, Backend/src/Controllers/controllersTecnologias.js, Backend/src/Controllers/controllersUser.js, Backend/src/Controllers/detail.js, Backend/src/Controllers/disableProduct.js, Backend/src/Controllers/ofertas.js, Backend/src/Controllers/searchName.js, Backend/src/Controllers/subcategorias.js, Backend/src/Controllers/verification.js, Backend/src/Database/DB_connection.js, Backend/src/Routes/carrito.js, Backend/src/Routes/index.js, Backend/src/Routes/tecnologia.js, Backend/src/Routes/userRouter.js, Backend/src/app.js
Estos cambios son para hacer el deploy del backend
=> Cambios para deploy del backend

Frontend/restore/src/app/form/page.jsx, Frontend/restore/src/app/user/page.jsx
creo que se puede deployar el front
=> Solucion para deploy front

Backend/src/Controllers/carrito.js, Backend/src/Database/models/Technology.js, Backend/src/Database/models/userModel.js, Backend/src/Routes/carrito.js
agregue el carrito en el esquema de user y ahora requiero por body los datos en ves de por cookies
=> Cambios en esquemas y controllers del carrito

Backend/src/Controllers/controllersUser.js, Backend/src/Routes/userRouter.js
Actualice la ruta para que se puedan actualizar todos los datos y la foto de perfil del usuario menos la constraseña
=> Actualizar user v2

Backend/package-lock.json, Backend/package.json, Backend/src/Controllers/UbicacionControllers.js, Backend/src/Controllers/controllersUser.js, Backend/src/Controllers/searchName.js, Backend/src/Database/models/userModel.js, Backend/src/Routes/tecnologia.js, Backend/src/Routes/userRouter.js, Frontend/restore/src/app/components/Ubicaciones/Ubicaciones.css, Frontend/restore/src/app/components/Ubicaciones/Ubicaciones.jsx, Frontend/restore/src/app/components/navbar/navbar.jsx, Frontend/restore/src/app/form/page.jsx, Frontend/restore/src/app/login/login.css, Frontend/restore/src/app/login/page.jsx, Frontend/restore/src/app/login/signup/page.jsx, Frontend/restore/src/app/user/page.jsx, Frontend/restore/src/app/user/ubicacion/form/form.css, Frontend/restore/src/app/user/ubicacion/form/page.jsx, Frontend/restore/src/app/user/ubicacion/page.jsx
1)Listos amobs sistemas de autenticacion
2)Botones de Google y Github
3)Varias funcionalidades de la NavBar
4) UserProfile logica completa de ubicaciones. Con pequelo Css orientativo
=> feat:Varias cosas

Frontend/restore/src/app/components/Ubicaciones/Ubicaciones.jsx, Frontend/restore/src/app/user/page.jsx, Frontend/restore/src/app/user/ubicacion/form/page.jsx
1)Solo se ve la informacion Accediendo por Local en el edit, pero no se puede editar porque rompe
2) Se agregaron botones de ir para Atras en ubicacion
=> fixingEdit

Frontend/restore/src/app/components/Ubicaciones/Ubicaciones.jsx, Frontend/restore/src/app/components/searchbar/searchbar.jsx, Frontend/restore/src/app/user/page.jsx, Frontend/restore/src/app/user/ubicacion/form/page.jsx
Se desabilita la SearchBar cuando esta en cualquier url de User
=> Fix search

Backend/package.json, Backend/src/Controllers/paymentsControllers.js, Backend/src/Database/models/order.js, Backend/src/Database/models/userModel.js, Backend/src/Routes/index.js, Backend/src/Routes/rutaPagos.js
pagos no terminados pero para implementar boton en el carrito
=> pagos no terminados pero para implementar boton en el carrito

Backend/package-lock.json, Backend/package.json, Backend/src/Controllers/paymentsControllers.js, Backend/src/Database/models/order.js, Backend/src/Routes/index.js, Backend/src/Routes/rutaPagos.js
Pasarela de pagos y información de los pagos realizados
=> stripe coco, ahora es personal

Backend/src/Controllers/paymentsControllers.js, Backend/src/Database/models/userModel.js, Backend/src/Routes/rutaPagos.js
agregue las ordenes al esquema de usuario y 
ya esta todo hecho para que pueda terminar los detalles tomas
=> solucion para el front

Backend/src/Controllers/controllersUser.js
=> problema modificar perfil

Frontend/restore/src/app/components/ProductsContainer/ProductsContainer.jsx, Frontend/restore/src/app/components/checkoutContent/CheckoutContent.jsx, Frontend/restore/src/app/components/loader/Loader.css, Frontend/restore/src/app/components/loader/Loader.jsx, Frontend/restore/src/app/home/[category]/page.jsx
=> Revert "Algunos estilos, filtros combinados"

Backend/src/Controllers/rating.js, Backend/src/Database/models/Technology.js, Backend/src/Routes/tecnologia.js, Frontend/restore/package-lock.json, Frontend/restore/src/app/dashboardadmin/clientes/page.jsx, Frontend/restore/src/app/dashboardadmin/inventario/page.jsx, Frontend/restore/src/app/ratingProduct/page.jsx, Frontend/restore/src/app/user/page.jsx
=> rating, falta css y agregar a detail

Backend/src/Controllers/controllersTecnologias.js, Backend/src/Database/models/Technology.js, Frontend/restore/src/app/form/page.jsx
=> Arreglo 2.0 mas arreglo que nunca

Backend/src/Controllers/envios.js, Frontend/restore/src/app/dashboardadmin/page.jsx, Frontend/restore/src/app/dashboardadmin/pedidos/page.jsx
=> Arreglo ordenes recientes

Frontend/restore/src/app/ratingProduct/page.jsx
=> pagina rating con detalle del producto
